max_brightness: 255

photo_loader:
  path: data/photos
  image_resize: 512
  extensions: [jpg, jpeg, png]

embedder:
  model_name: ViT-B/32
  embedding_size: 512
  download_root: clip

superlinked:
  limit: 6
  put_batch_size: 1

reranker:
  openai_url: https://api.openai.com/v1/chat/completions
  model_name: cross-encoder/ms-marco-TinyBERT-L-2-v2
